import { withTestVoiceCasting } from '../automatic-complete-engines.js';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { expect, test } from '@playwright/test';
import { AutomationService } from '../../src/automation/service.js';
import { buildForSpeechVoice } from '../../src/build.js';
import { CodexRequestStore } from '../../src/codex/requests.js';
import { createApp } from '../../src/server/app.js';
import type { AppConfig } from '../../src/server/config.js';
import { createExecutionHarness } from '../automatic-executor-helpers.js';
import { TEST_AUDIO_NORMALIZATION_OPTIONS } from '../helpers.js';

test('e2e_automatic_production_start_to_pending_image_review_preserves_final_gate', async ({ page }): Promise<void> => {
  const h = await createExecutionHarness(async (): Promise<void> => {});
  const root = await mkdtemp(join(tmpdir(), 'cutroom-automatic-ui-'));
  const service = new AutomationService({ services: { ...h.services, engines: () => withTestVoiceCasting(h.engine) }, onError: (_id, problem): void => { throw new Error(problem.message); } });
  await service.initialize(); await service.cancel(h.source.projectId, h.id);
  const config: AppConfig = { host: '127.0.0.1', port: 4317, dataRoot: join(root, 'unused-data'), webRoot: resolve('dist/web'),
    pdfFontPath: resolve('assets/fonts/NanumGothic-Regular.ttf'), audioNormalization: TEST_AUDIO_NORMALIZATION_OPTIONS,
    codex: { requestRoot: join(root, 'requests'), speechVoice: 'Yuna' } };
  const app = await createApp(config, h.services.projects, new CodexRequestStore(config.codex.requestRoot, buildForSpeechVoice('Yuna')), undefined, undefined, service);
  try {
    await page.goto(await app.listen({ host: '127.0.0.1', port: 0 }));
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '제작 현황', exact: true }).click();
    const panel = page.getByRole('region', { name: 'Codex 자동 제작' });
    await expect(panel.getByLabel('음성 제작', { exact: true })).toHaveValue('instructions-only');
    await panel.getByLabel('음성 제작', { exact: true }).selectOption('guide-voice');
    await panel.getByText('제작 범위와 실행 설정', { exact: false }).click();
    await panel.getByLabel('컷·그림 표현 수준').selectOption('detailed');
    await panel.getByLabel('같은 그림 표시 검토 기준 ms').fill('5000');
    const checkboxes = panel.locator('.automatic-segment input');
    for (let index: number = 0; index < h.source.dataset.segments.length; index += 1) await checkboxes.nth(index).setChecked(h.source.dataset.segments[index]!.id === 'demonstration');
    await page.reload();
    await expect(panel).toBeVisible();
    await panel.getByText('제작 범위와 실행 설정', { exact: false }).click();
    await expect(panel.getByLabel('컷·그림 표현 수준')).toHaveValue('detailed');
    await expect(panel.getByLabel('같은 그림 표시 검토 기준 ms')).toHaveValue('5000');
    await expect(panel.locator('.automatic-segment input:checked')).toHaveCount(1);
    expect(await service.list(h.source.projectId)).toHaveLength(1);
    expect((await h.services.projects.read(h.source.projectId)).revision).toBe(0);
    await panel.getByRole('button', { name: '1개 구간 자동 제작 시작', exact: true }).click();
    await expect(panel.getByText('생성 결과 검토 대기', { exact: true })).toBeVisible({ timeout: 20000 });
    await expect(panel.getByText('7 / 현재 등록 7개 반영', { exact: false })).toBeVisible();
    await panel.getByRole('button', { name: '생성 결과 불러와 검토' }).click();
    const monitor = page.getByRole('dialog', { name: '콘티 시간순 재생' });
    await expect(monitor).toContainText('제작자 검토 · 미승인 결과 포함');
    await monitor.getByRole('button', { name: 'CLOSE', exact: true }).click();
    const densityReview = panel.getByRole('region', { name: '콘티 표현 검토' });
    await expect(densityReview).toContainText('1컷 · 프레임 1개 · 그림 대상 1개');
    await expect(densityReview).toContainText('긴 그림 표시 검토 1개');
    await densityReview.getByText('긴 그림 표시 구간 확인', { exact: true }).click();
    await densityReview.getByRole('button', { name: '이 컷 검토', exact: true }).click();
    await expect(page.getByRole('navigation', { name: '선택 컷 편집 항목' }).getByRole('button', { name: '그림', exact: true })).toHaveAttribute('aria-current', 'page');
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '컷 편집', exact: true }).click();
    await page.getByRole('navigation', { name: '선택 컷 편집 항목' }).getByRole('button', { name: '그림', exact: true }).click();
    const index = h.source.dataset.segments.findIndex((segment): boolean => segment.id === 'demonstration');
    await page.locator('.scene-rail button').nth(index).click();
    const preview = page.locator('.frame-review-preview');
    await expect(preview).toContainText('미승인 그림');
    await expect(preview.locator('img')).toBeVisible();
    await expect(preview.locator('img')).toHaveJSProperty('naturalWidth', 90);
    await expect(page.getByRole('region', { name: 'Final Readiness' })).toContainText('초안 작업 중');
    await page.getByRole('navigation', { name: '선택 컷 편집 항목' }).getByRole('button', { name: '음성', exact: true }).click();
    const audio = page.locator('audio[data-storyboard-review]');
    await expect(audio).toBeVisible(); await expect(audio).toHaveJSProperty('duration', 2.3);
    await expect(audio).toHaveJSProperty('volume', Math.pow(10, -3 / 20));
    const mixEditor = page.locator('.audio-mix-editor').first();
    await expect(mixEditor.getByLabel('음량 (dB)')).toHaveValue('-3');
    await mixEditor.getByText('자동 음량 검토 근거').click();
    await expect(mixEditor).toContainText('RMS');
    await mixEditor.getByText('자동 음량 검토 근거').click();
    await mixEditor.getByLabel('음량 (dB)').scrollIntoViewIfNeeded();
    await expect(mixEditor.getByLabel('음량 (dB)')).toBeInViewport();
    await page.screenshot({ path: '.local/validation/automation-runtime/audio-mix-settings-ui.png' });
    await page.locator('.audio-review-preview').getByLabel('청취 음량').selectOption('source');
    await expect(audio).toHaveJSProperty('volume', 1);
    await page.locator('.audio-review-preview').getByLabel('청취 음량').selectOption('saved');
    await expect(audio).toHaveJSProperty('volume', Math.pow(10, -3 / 20));
    await audio.scrollIntoViewIfNeeded(); await expect(audio).toBeInViewport();
    await audio.evaluate(async (element: HTMLAudioElement): Promise<void> => { await element.play(); });
    await expect(audio).toHaveJSProperty('paused', false);
    await page.screenshot({ path: '.local/validation/automation-runtime/audio-mix-review-ui.png' });
    await page.getByRole('navigation', { name: '선택 컷 편집 항목' }).getByRole('button', { name: '그림', exact: true }).click();
    await expect(audio).toHaveCount(0);
    await page.getByRole('navigation', { name: '선택 컷 편집 항목' }).getByRole('button', { name: '음성', exact: true }).click();
    await expect(audio).toHaveJSProperty('paused', true);
    await mixEditor.getByLabel('음량 (dB)').fill('-9');
    await mixEditor.getByRole('button', { name: '음량 설정 저장' }).click();
    await expect(mixEditor.getByLabel('음량 계획')).toHaveValue('manual');
    await expect(audio).toHaveJSProperty('volume', Math.pow(10, -9 / 20));
    await page.reload();
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '컷 편집', exact: true }).click();
    await page.locator('.scene-rail button').nth(index).click();
    await page.getByRole('navigation', { name: '선택 컷 편집 항목' }).getByRole('button', { name: '음성', exact: true }).click();
    await expect(mixEditor.getByLabel('음량 (dB)')).toHaveValue('-9');
    await expect(mixEditor.getByLabel('음량 계획')).toHaveValue('manual');
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '제작 현황', exact: true }).click();
    await expect(audio).toHaveCount(0);
    const current = await h.services.projects.read(h.source.projectId);
    expect(current.revision).toBe(8); expect(current.dataset).toEqual(h.source.dataset);
    expect(current.textLayout.fontSize).toBe(0.045); expect(current.textCues).toEqual(h.source.textCues);
    expect(current.frames.filter((frame): boolean => frame.imageAssetId !== null).every((frame): boolean => frame.visualReview === 'pending')).toBe(true);
    expect(current.voiceCasting?.assignments).toMatchObject([{ speakerId: 'CHAR-01', voice: { name: 'Yuna', rateWordsPerMinute: 180 } }]);
    expect(current.generationRecords.filter((record): boolean => record.templateVersion === 'automatic-voice-casting-1.0.0')).toHaveLength(1);
    const savedRun = (await service.list(h.source.projectId)).find((run): boolean => run.status === 'review-ready')!;
    expect(savedRun.settings).toMatchObject({ textLayoutPlanning: 'automatic', audioMixPlanning: 'automatic', density: { detail: 'detailed', longHoldReviewMs: 5000 } });
    const planRecord = current.generationRecords.find((record): boolean => record.templateVersion === 'automatic-segment-plan-1.0.0')!;
    expect(JSON.parse(planRecord.prompt).densityReview).toMatchObject({ policy: { detail: 'detailed', longHoldReviewMs: 5000 }, frameCount: 1 });
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '제작 설정', exact: true }).click();
    const layout = page.getByRole('form', { name: '글자 배치 설정' });
    await expect(layout.getByLabel('배치 설정 방식')).toHaveValue('automatic');
    await expect(layout.getByLabel('글자 크기 · 짧은 변의 %')).toHaveValue('4.5');
    await expect(layout.getByRole('region', { name: '최근 자동 글자 배치' })).toContainText('문구 길이와 세로 화면비에 맞춰 글자 크기를 정했습니다.');
    await layout.scrollIntoViewIfNeeded(); await page.screenshot({ path: '.local/validation/automation-runtime/text-preset-browser.png' });
    await layout.getByRole('region', { name: '최근 자동 글자 배치' }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: '.local/validation/automation-runtime/text-preset-review-browser.png' });
    await layout.getByLabel('글자 크기 · 짧은 변의 %').fill('5');
    await expect(layout.getByLabel('배치 설정 방식')).toHaveValue('manual');
    await layout.getByRole('button', { name: '글자 배치 저장' }).click();
    await expect(layout.getByRole('region', { name: '최근 자동 글자 배치' })).toContainText('제안 이후 배치 설정이 변경됐습니다.');
    await page.reload();
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '제작 설정', exact: true }).click();
    await expect(layout.getByLabel('배치 설정 방식')).toHaveValue('manual');
    await expect(layout.getByLabel('글자 크기 · 짧은 변의 %')).toHaveValue('5');
    await page.getByRole('navigation', { name: '콘티 작업 공간' }).getByRole('button', { name: '제작 현황', exact: true }).click();
    await panel.getByText('제작 범위와 실행 설정', { exact: false }).click();
    await expect(panel.getByLabel('컷·그림 표현 수준')).toHaveValue('detailed');
    await expect(panel.getByLabel('같은 그림 표시 검토 기준 ms')).toHaveValue('5000');
    await panel.getByLabel('컷·그림 표현 수준').scrollIntoViewIfNeeded();
    await page.screenshot({ path: '.local/validation/automation-runtime/storyboard-density-browser.png' });
  } finally { await page.context().close(); await app.close(); await h.close(); await rm(root, { recursive: true, force: true }); }
});
