import { cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { expect, test } from '@playwright/test';
import { readBuildManifest } from '../../src/build.js';
import { CodexRequestStore } from '../../src/codex/requests.js';
import { readPackage } from '../../src/io/package.js';
import { createApp } from '../../src/server/app.js';
import { ProjectStore } from '../../src/server/store.js';
import { PRODUCTION_DOCUMENT_BINDINGS, SYNTHETIC_DOCUMENT_BINDINGS } from '../document-helpers.js';
import { TEST_AUDIO_NORMALIZATION_OPTIONS } from '../helpers.js';

test('e2e_eight_documents_review_settings_package_and_storyboard_import', async ({ page }, testInfo): Promise<void> => {
  const root: string = await mkdtemp(join(tmpdir(), 'document-e2e-'));
  const input: string = join(root, 'input'); await cp('tests/fixtures/production/09_PRODUCTION', input, { recursive: true });
  const store = new ProjectStore(join(root, 'data'));
  const app = await createApp({ host: '127.0.0.1', port: 4317, dataRoot: join(root, 'data'), webRoot: resolve('dist/web'),
    pdfFontPath: resolve('assets/fonts/NanumGothic-Regular.ttf'), audioNormalization: TEST_AUDIO_NORMALIZATION_OPTIONS,
    codex: { requestRoot: join(root, 'requests'), speechVoice: 'Yuna' } }, store, new CodexRequestStore(join(root, 'requests'), readBuildManifest()));
  try {
    const url: string = await app.listen({ host: '127.0.0.1', port: 0 }); await page.goto(url);
    await page.locator('.welcome').getByRole('button', { name: /제작 문서 8개/ }).click();
    const panel = page.getByRole('dialog');
    await panel.getByLabel('제작 문서 폴더').fill(input);
    await panel.getByRole('button', { name: '문서 검토', exact: true }).click();
    await expect(panel).toContainText('12장면 · 32구간 · 원문 95개');
    await expect(panel.getByLabel('프레임레이트', { exact: true })).toHaveValue('');
    await expect(panel.getByRole('button', { name: '패키지 생성', exact: true })).toHaveCount(0);
    await expect(panel.getByRole('status')).toContainText('연결 확인 필요 5개');
    await page.screenshot({ path: testInfo.outputPath('document-import-desktop.png') });
    for (const binding of PRODUCTION_DOCUMENT_BINDINGS.people) await panel.getByLabel(`인물 ID: ${binding.key}`, { exact: true }).selectOption(binding.targetId);
    await panel.getByLabel('프레임레이트', { exact: true }).selectOption('25/1');
    await panel.getByLabel('음성 샘플레이트', { exact: true }).selectOption('44100');
    await panel.getByLabel('화면비 가로', { exact: true }).fill('9');
    await panel.getByLabel('화면비 세로', { exact: true }).fill('16');
    await panel.getByRole('button', { name: '생성 내용 확인', exact: false }).click();
    await panel.getByLabel('패키지 버전', { exact: true }).fill('e2e-explicit-settings');
    await panel.getByLabel('새 패키지 폴더', { exact: true }).fill(join(root, 'package'));
    await panel.getByRole('button', { name: '패키지 생성', exact: true }).click();
    await expect(panel.getByRole('status')).toContainText('패키지 생성 완료');
    await page.screenshot({ path: testInfo.outputPath('document-package-created.png') });
    const payload = await readPackage(join(root, 'package', 'storyboard_handoff.json'));
    expect(payload.handoff.profile.aspectWidth).toBe(9);
    expect(payload.handoff.timebase.fpsNumerator).toBe(25);
    await panel.getByLabel('초안 글자 유지 시간 (ms)', { exact: true }).fill('2000');
    await panel.getByRole('button', { name: '생성 패키지 불러오기', exact: true }).click();
    await expect(page.locator('.app-shell')).toBeVisible();
    const project = await store.read('PRJ-007');
    expect(project.dataset.units).toHaveLength(95);
    expect(project.handoff.adapter).toBe('production-documents-v1');
    expect(project.shots).toHaveLength(32);
    await page.reload();
    await expect(page.getByRole('button', { name: /의부증의 늪/ }).first()).toBeVisible();
    await page.getByRole('button', { name: /의부증의 늪/ }).first().click();
    const secondInput: string = join(root, 'second-input'); await cp('tests/fixtures/documents', secondInput, { recursive: true });
    await page.getByRole('button', { name: /제작 문서 8개/ }).click();
    const secondPanel = page.getByRole('dialog');
    await secondPanel.getByLabel('제작 문서 폴더').fill(secondInput);
    await secondPanel.getByRole('button', { name: '문서 검토', exact: true }).click();
    await expect(secondPanel).toContainText('2장면 · 2구간 · 원문 4개');
    for (const binding of SYNTHETIC_DOCUMENT_BINDINGS.people) await secondPanel.getByLabel(`인물 ID: ${binding.key}`, { exact: true }).selectOption(binding.targetId);
    for (const binding of SYNTHETIC_DOCUMENT_BINDINGS.scenes) await secondPanel.getByLabel(`장면 ID: ${binding.key}`, { exact: true }).selectOption(binding.targetId);
    await secondPanel.getByRole('button', { name: '연결 다시 확인', exact: true }).click();
    await expect(secondPanel.getByRole('status')).toContainText('모든 연결을 확인했습니다.');
    await secondPanel.getByLabel('프레임레이트', { exact: true }).selectOption('30/1');
    await secondPanel.getByLabel('음성 샘플레이트', { exact: true }).selectOption('48000');
    await secondPanel.getByLabel('화면비 가로', { exact: true }).fill('16');
    await secondPanel.getByLabel('화면비 세로', { exact: true }).fill('9');
    await secondPanel.getByRole('button', { name: '생성 내용 확인', exact: false }).click();
    await secondPanel.getByLabel('패키지 버전', { exact: true }).fill('second-story');
    await secondPanel.getByLabel('새 패키지 폴더', { exact: true }).fill(join(root, 'second-package'));
    await secondPanel.getByRole('button', { name: '패키지 생성', exact: true }).click();
    await expect(secondPanel.getByRole('status')).toContainText('패키지 생성 완료');
    await secondPanel.getByLabel('초안 글자 유지 시간 (ms)', { exact: true }).fill('1500');
    await secondPanel.getByRole('button', { name: '생성 패키지 불러오기', exact: true }).click();
    await expect(page.locator('.project-tile')).toHaveCount(2);
    expect((await store.read('plant-doc-demo')).dataset.units).toHaveLength(4);
    expect((await store.read('PRJ-007')).dataset.units).toHaveLength(95);
    await page.getByRole('textbox', { name: 'ACTION', exact: true }).fill('저장하지 않은 편집 내용');
    const opener = page.getByRole('button', { name: /제작 문서 8개/ });
    await opener.click();
    await secondPanel.getByLabel('제작 문서 폴더').fill(secondInput);
    await secondPanel.getByRole('button', { name: '문서 검토', exact: true }).click();
    await expect(secondPanel).toContainText('이미 저장된 프로젝트입니다');
    await expect(secondPanel.getByRole('button', { name: '생성 패키지 불러오기', exact: true })).toHaveCount(0);
    await page.keyboard.press('Escape');
    await expect(opener).toBeFocused();
    await expect(page.getByRole('textbox', { name: 'ACTION', exact: true })).toHaveValue('저장하지 않은 편집 내용');
    await opener.click();
    await expect(secondPanel).toContainText('연결과 제작 기준을 확인하세요');
    await expect(secondPanel).toContainText('이미 저장된 프로젝트입니다');
    expect((await store.read('plant-doc-demo')).revision).toBe(0);
  } finally { await page.context().close(); await app.close(); await rm(root, { recursive: true, force: true }); }
});

test('e2e_document_workflow_mobile_validation_changed_source_and_retry', async ({ page }, testInfo): Promise<void> => {
  const root: string = await mkdtemp(join(tmpdir(), 'document-ui-e2e-'));
  const input: string = join(root, 'input'); await cp('tests/fixtures/documents', input, { recursive: true });
  const store = new ProjectStore(join(root, 'data'));
  const app = await createApp({ host: '127.0.0.1', port: 4317, dataRoot: join(root, 'data'), webRoot: resolve('dist/web'),
    pdfFontPath: resolve('assets/fonts/NanumGothic-Regular.ttf'), audioNormalization: TEST_AUDIO_NORMALIZATION_OPTIONS,
    codex: { requestRoot: join(root, 'requests'), speechVoice: 'Yuna' } }, store, new CodexRequestStore(join(root, 'requests'), readBuildManifest()));
  try {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(await app.listen({ host: '127.0.0.1', port: 0 }));
    await page.locator('.rail-document-entry').click();
    const panel = page.getByRole('dialog');
    await panel.getByRole('button', { name: '문서 검토', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('폴더 경로를 입력하세요');
    await panel.getByRole('alert').getByRole('button').click();
    await expect(panel.getByLabel('제작 문서 폴더')).toBeFocused();
    await panel.getByLabel('제작 문서 폴더').fill(input);
    await panel.getByRole('button', { name: '문서 검토', exact: true }).click();
    await expect(panel).toContainText('2장면 · 2구간 · 원문 4개');
    await panel.getByLabel('인물 ID: 민아', { exact: true }).selectOption('host');
    await panel.getByLabel('인물 ID: 준', { exact: true }).selectOption('host');
    for (const binding of SYNTHETIC_DOCUMENT_BINDINGS.scenes) await panel.getByLabel('장면 ID: ' + binding.key, { exact: true }).selectOption(binding.targetId);
    await panel.getByRole('button', { name: '생성 내용 확인', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('다른 항목에도 선택');
    await expect(panel.getByRole('alert')).toContainText('프레임레이트를 선택하세요');
    await panel.getByRole('alert').getByRole('button', { name: '프레임레이트를 선택하세요.' }).click();
    await expect(panel.getByLabel('프레임레이트', { exact: true })).toBeFocused();
    await panel.getByLabel('인물 ID: 준', { exact: true }).selectOption('helper');
    await panel.getByLabel('프레임레이트', { exact: true }).selectOption('24/1');
    await panel.getByLabel('음성 샘플레이트', { exact: true }).selectOption('48000');
    await panel.getByLabel('화면비 가로', { exact: true }).fill('16385');
    await panel.getByLabel('화면비 세로', { exact: true }).fill('9');
    await panel.getByRole('button', { name: '생성 내용 확인', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('1~16384');
    await panel.getByLabel('화면비 가로', { exact: true }).fill('16');
    await panel.getByRole('button', { name: '이전 단계', exact: true }).click();
    await panel.getByRole('button', { name: '문서 검토', exact: true }).click();
    await expect(panel.getByLabel('인물 ID: 준', { exact: true })).toHaveValue('helper');
    await expect(panel.getByLabel('프레임레이트', { exact: true })).toHaveValue('24/1');
    await panel.getByRole('button', { name: '생성 내용 확인', exact: true }).click();
    await panel.getByRole('button', { name: '패키지 생성', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('패키지 버전을 입력하세요');
    await panel.getByLabel('패키지 버전', { exact: true }).fill('mobile-review');
    await panel.getByLabel('새 패키지 폴더', { exact: true }).fill(root);
    await panel.getByRole('button', { name: '패키지 생성', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('존재');
    await panel.getByLabel('새 패키지 폴더', { exact: true }).fill(join(root, 'package'));
    await writeFile(join(input, 'narration.md'), await readFile(join(input, 'narration.md'), 'utf8') + '\n검토 뒤 문서 변경\n');
    await panel.getByRole('button', { name: '패키지 생성', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('검토 이후 입력 문서가 변경');
    await panel.getByRole('button', { name: '이전 단계', exact: true }).click();
    await panel.getByRole('button', { name: '생성 내용 확인', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('검토 이후 원본 문서가 변경');
    await panel.getByRole('button', { name: '이전 단계', exact: true }).click();
    await panel.getByRole('button', { name: '문서 검토', exact: true }).click();
    for (const binding of SYNTHETIC_DOCUMENT_BINDINGS.people) await panel.getByLabel('인물 ID: ' + binding.key, { exact: true }).selectOption(binding.targetId);
    for (const binding of SYNTHETIC_DOCUMENT_BINDINGS.scenes) await panel.getByLabel('장면 ID: ' + binding.key, { exact: true }).selectOption(binding.targetId);
    await panel.getByRole('button', { name: '생성 내용 확인', exact: true }).click();
    await panel.getByRole('button', { name: '패키지 생성', exact: true }).click();
    await expect(panel.getByRole('status')).toContainText('패키지 생성 완료');
    await panel.getByRole('button', { name: '생성 패키지 불러오기', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('초안 글자 유지 시간');
    await panel.getByLabel('초안 글자 유지 시간 (ms)', { exact: true }).fill('1500');
    await page.route('**/api/projects/import', async (route): Promise<void> => { await route.abort('failed'); });
    await panel.getByRole('button', { name: '생성 패키지 불러오기', exact: true }).click();
    await expect(panel.getByRole('alert')).toContainText('서버에 연결하지 못했습니다');
    await expect(panel.locator('.document-success')).toContainText('storyboard_handoff.json');
    expect(await panel.evaluate((element: HTMLDialogElement): boolean => element.scrollWidth <= element.clientWidth)).toBe(true);
    expect(await panel.locator('.document-scroll').evaluate((element: HTMLDivElement): boolean => element.scrollWidth <= element.clientWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('document-import-mobile.png') });
    await page.unroute('**/api/projects/import');
    await panel.getByRole('button', { name: '생성 패키지 불러오기', exact: true }).click();
    await expect(panel).not.toBeVisible();
    expect((await store.read('plant-doc-demo')).dataset.units).toHaveLength(4);
  } finally { await page.context().close(); await app.close(); await rm(root, { recursive: true, force: true }); }
});
