import { readdir, readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { contractError } from '../src/domain/errors.js';

const REQUIRED_TEST_NAMES: readonly string[] = [
  'internal_bundle_preserves_full_review_content',
  'external_bundle_removes_source_snapshot_content',
  'external_bundle_removes_generation_prompts',
  'external_bundle_removes_absolute_paths',
  'external_bundle_redacts_email_and_phone',
  'external_csv_uses_redacted_projection',
  'external_pdf_uses_redacted_projection',
  'external_bundle_rejects_include_media',
  'external_bundle_uses_image_placeholders',
  'redaction_manifest_contains_hashes_but_not_raw_values',
  'external_bundle_does_not_modify_source_project',

  'project_list_reuses_integrity_cache_for_unchanged_asset',
  'integrity_cache_invalidates_on_inode_change',
  'integrity_cache_invalidates_on_size_or_mtime_change',
  'new_asset_does_not_reuse_old_cache_entry',
  'final_readiness_forces_asset_revalidation',
  'safe_visual_forces_asset_revalidation',
  'safe_audio_forces_asset_revalidation',
  'review_bundle_forces_asset_revalidation',
  'cached_summary_cannot_make_corrupt_asset_safe',

  'status_discovers_external_create_started_after_initialize',
  'status_discovers_external_update_started_after_initialize',
  'status_discovers_lock_not_present_in_memory_map',
  'malformed_locked_project_does_not_fail_global_status',
  'status_continues_reporting_healthy_projects',
  'status_does_not_delete_live_external_lock',
  'recovered_external_lock_does_not_reappear',
  'invalid_audio_range_returns_416_with_content_range',
  'unsatisfiable_suffix_range_returns_416_with_full_size',
  'multi_range_request_is_rejected_with_content_range',
  'valid_partial_audio_range_returns_206',
  'full_audio_request_returns_200_with_accept_ranges',

  'review_bundle_is_stable_with_unsorted_directory_entries',
  'source_hashes_use_canonical_key_order',
  'asset_manifest_uses_deterministic_asset_order',
  'asset_generation_links_use_introduced_revision_order',
  'bundle_json_uses_stable_recursive_serialization',
  'cross_platform_bundle_manifest_is_reproducible',
  'bundle_bytes_are_equal_for_shuffled_version_creation_order',
  'bundle_builder_build_is_not_labeled_as_generation_build',
  'generation_build_summary_counts_known_builds',
  'generation_build_summary_preserves_unknown_legacy_records',
  'asset_manifest_links_assets_to_actual_generation_records',
  'unlinked_assets_are_reported_without_fabricated_build',

  'final_bundle_rejects_pending_transaction',
  'final_bundle_rejects_active_project_lock',
  'final_bundle_rejects_active_create_lock',
  'final_bundle_rejects_future_uncommitted_version',
  'final_bundle_rejects_recovery_blocked_store',
  'draft_bundle_reports_nonquiescent_storage',
  'review_bundle_does_not_modify_recovery_evidence',
  'review_bundle_detects_transaction_created_during_export',
  'failed_final_bundle_creates_no_output_directory',

  'cut_has_no_early_incoming_exposure',
  'fade_to_black_has_no_early_incoming_exposure',
  'dissolve_exposes_incoming_from_transition_start',
  'wipe_exposes_incoming_from_transition_start',
  'match_cut_exposes_incoming_from_transition_start',
  'custom_transition_requires_explicit_visual_policy',
  'fade_through_black_exposes_incoming_after_midpoint',
  'transition_preview_and_final_readiness_share_policy',
  'transition_information_gate_uses_actual_incoming_reveal_time',

  'head_commit_sha_is_preserved_when_worktree_is_dirty',
  'unrelated_untracked_file_does_not_erase_head_commit',
  'generation_input_change_sets_generation_inputs_dirty',
  'skill_change_changes_generation_contract_hash',
  'agents_change_changes_generation_contract_hash',
  'speech_voice_change_changes_runtime_generation_config_hash',
  'secret_and_absolute_path_are_not_hashed_into_manifest',
  'build_fingerprint_is_stable_across_path_separator',
  'legacy_generator_build_migrates_without_fabrication',
  'project_17_to_18_migration_preserves_original_data',
  'pending_request_from_old_build_is_not_reused',
  'same_build_pending_request_is_reused',
  'new_build_supersedes_old_pending_request',
  'superseded_request_is_preserved_for_audit',
  'superseded_request_is_excluded_from_operational_failure_rate',
  'skill_change_requires_new_request',
  'speech_voice_change_requires_new_speech_request',
  'legacy_pending_request_without_fingerprint_is_not_reused',


  'sourced_to_black_is_applied_atomically',
  'sourced_to_hold_previous_is_applied_atomically',
  'black_to_sourced_adds_visual_sources_atomically',
  'hold_previous_to_sourced_adds_visual_sources_atomically',
  'visual_plan_rejects_direct_sources_for_black',
  'visual_plan_rejects_direct_sources_for_hold',
  'visual_plan_rejects_sourced_coverage_gap',
  'visual_plan_respects_sources_and_frames_locks',
  'failed_visual_plan_change_leaves_project_unchanged',
  'visual_plan_change_invalidates_approval_and_frames',
  'visual_plan_http_update_increments_one_revision',
  'web_visual_plan_uses_single_mutation',
  'legacy_mode_only_update_returns_actionable_error',
  'manual_anchor_change_cannot_reverse_first_visual_reveal',
  'manual_source_move_cannot_reverse_first_visual_reveal',
  'validation_uses_temporal_first_reveal_order',
  'approval_blocks_temporal_source_order_reversal',
  'final_readiness_blocks_temporal_source_order_reversal',
  'proposal_and_manual_edit_share_first_reveal_policy',
  'continued_visual_reappearance_does_not_reset_manual_order',
  'simultaneous_first_reveal_is_not_reversed',
  'unresolved_anchor_is_not_treated_as_zero_time',

  'proposed_text_is_allowed_in_draft_preview',
  'proposed_text_is_blocked_in_final_output',
  'confirmed_text_is_safe_in_final_output',
  'final_pdf_rejects_unconfirmed_text',
  'final_csv_marks_unconfirmed_text_as_blocked',
  'project_final_readiness_requires_confirmed_text',
  'draft_export_marks_proposed_text_as_draft',
  'final_export_succeeds_after_text_confirmation',
  'manual_source_edit_cannot_introduce_visual_coverage_gap',
  'manual_source_edit_may_reduce_existing_visual_coverage_gap',
  'manual_anchor_move_invalidates_visual_coverage',
  'source_move_checks_both_source_and_target_coverage',
  'sourced_gap_blocks_shot_approval',
  'program_monitor_blocks_visual_gap_at_actual_playhead',
  'safe_visual_output_uses_actual_playhead',
  'readiness_excludes_sourced_visual_gap',
  'pdf_marks_sourced_visual_gap_as_blocked',
  'csv_marks_sourced_visual_gap_as_blocked',
  'first_shot_hold_previous_cannot_be_approved',
  'noncontiguous_hold_previous_cannot_be_approved',
  'hold_previous_requires_safe_source_for_final_output',
  'hold_previous_source_gap_predecessor_is_not_output_ready',
  'hold_previous_pending_predecessor_is_not_output_ready',
  'hold_previous_rejected_predecessor_is_not_output_ready',
  'hold_previous_may_resolve_black_predecessor',
  'chained_hold_previous_resolves_to_safe_origin',
  'frame_anchor_reveal_does_not_create_one_millisecond_visual',
  'frame_anchor_visual_range_persists_to_declared_end',
  'coverage_uses_visual_interval_not_reveal_point',
  'later_frame_context_keeps_active_frame_anchored_source',
  'ambiguous_frame_anchor_interval_requires_review',
  'legacy_frame_anchor_migration_preserves_source_and_timing',
  'migrated_unresolved_frame_anchor_blocks_output',
  'distinct_permille_frames_cannot_collapse_silently',
  'explicit_frame_may_replace_derived_anchor_frame',
  'two_explicit_frames_at_same_millisecond_are_rejected',
  'short_shot_frame_plan_preserves_semantic_points',
  'continued_visual_after_later_primary_is_allowed',
  'source_order_uses_first_reveal_per_unit',
  'continued_visual_does_not_reset_unit_order',
  'first_visual_reveal_order_reversal_is_rejected',
  'audit_deduplicates_current_revision_snapshot',
  'audit_rejects_stable_current_version_mismatch',
  'audit_records_only_absent_to_present_reappearance',
  'audit_does_not_repeat_reappearance_for_continuous_presence',
  'audit_target_history_starts_at_introduced_revision',
  'invalid_introduction_target_is_unresolved_not_historical',
  'audit_revision_arrays_are_unique_and_sorted',
  'audit_still_detects_removed_mutated_and_reappeared_records',
  'status_does_not_hide_unverifiable_active_update',
  'status_converts_corrupt_update_lock_to_project_recovery_state',
  'foreign_active_update_remains_visible',
  'active_update_error_is_project_scoped',
  'unrelated_project_continues_during_active_update_error',
  'status_refresh_is_idempotent_after_update_recovery',
  'e2e_real_wav_decodes_in_chromium',
  'e2e_real_audio_loadedmetadata_reports_duration',
  'e2e_real_audio_seek_uses_html_media_element',
  'e2e_real_audio_stops_at_cue_end',
  'e2e_real_audio_is_disposed_on_monitor_close',
  'e2e_real_audio_is_disposed_on_project_switch',
  'new_generation_record_contains_build_provenance',
  'legacy_generation_record_migrates_build_to_null',
  'status_exposes_build_provenance',
  'review_bundle_contains_required_files',
  'review_bundle_manifest_contains_file_hashes',
  'review_bundle_does_not_modify_project',
  'final_review_bundle_requires_final_readiness',
  'draft_review_bundle_reports_unconfirmed_text',
  'review_bundle_excludes_media_by_default',
  'review_bundle_includes_media_only_when_requested',
  'prj007_draft_output_remains_available',
  'prj007_final_output_requires_confirmed_text',
  'prj007_visual_timeline_is_playhead_safe',
  'prj007_hold_previous_contract_remains_valid',
  'prj007_generation_audit_remains_valid',
  'prj007_review_bundle_is_reproducible',
  'prj007_unit045_safe_audio_remains_valid',

  'proposal_frames_accept_optional_plan',
  'legacy_proposal_without_frames_remains_compatible',
  'project_1_5_migrates_visual_mode_to_sourced',
  'schema_1_6_round_trip_preserves_visual_mode',
  'sourced_shot_requires_start_frame_at_zero',
  'late_source_anchor_creates_key_frame',
  'key_frame_offset_matches_anchor_start',
  'key_frame_context_includes_newly_active_source',
  'early_frame_context_excludes_future_source',
  'key_frame_context_respects_information_gate',
  'sourced_visual_coverage_rejects_start_gap',
  'sourced_visual_coverage_rejects_middle_gap',
  'sourced_visual_coverage_accepts_adjacent_half_open_ranges',
  'black_visual_mode_allows_no_direct_visual_source',
  'black_mode_disables_image_generation',
  'black_mode_renders_deterministic_output',
  'hold_previous_mode_requires_previous_contiguous_shot',
  'hold_previous_uses_previous_output_safe_frame',
  'hold_previous_without_safe_frame_is_blocked',
  'non_sourced_mode_rejects_direct_visual_links',
  'proposal_information_without_source_does_not_report_infinity',
  'periodic_heartbeat_starts_after_initialize',
  'periodic_heartbeat_keeps_long_transaction_live',
  'periodic_heartbeat_is_shared_per_root_and_instance',
  'periodic_heartbeat_timer_is_unrefed',
  'periodic_heartbeat_stops_after_last_store_close',
  'heartbeat_failure_is_exposed_in_status',
  'audit_scans_union_of_all_version_record_ids',
  'audit_reports_record_removed_before_current',
  'audit_detects_intermediate_metadata_mutation',
  'audit_detects_record_reappearance',
  'audit_reports_mixed_current_and_historical_shot_targets',
  'audit_reports_historical_asset_targets',
  'audit_uses_consistent_current_and_version_snapshot',
  'audit_retries_once_when_current_changes',
  'audit_returns_conflict_when_snapshot_keeps_changing',
  'audit_does_not_modify_project_or_versions',
  'malformed_recovery_marker_is_quarantined',
  'invalid_recovery_marker_does_not_block_unrelated_project_list',
  'invalid_recovery_marker_does_not_block_unrelated_update',
  'invalid_recovery_marker_does_not_block_unrelated_create',
  'status_exposes_invalid_recovery_markers',
  'valid_recovery_marker_still_blocks_only_own_project',
  'stored_asset_path_unsafe_returns_asset_scope_423',
  'stored_asset_symlink_error_is_not_validation_400',
  'stored_asset_path_issue_does_not_block_project_mutation',
  'asset_integrity_endpoint_reports_current_output_references',
  'asset_integrity_reconcile_clears_repaired_asset',
  'unreferenced_historical_corrupt_asset_does_not_keep_current_ui_banner',
  'project_refresh_reconciles_asset_integrity_issues',
  'open_ended_placement_uses_explicit_text_cue_end',
  'open_ended_placement_uses_canonical_end_when_no_cue_end',
  'open_ended_placement_without_resolved_end_requires_review',
  'expired_open_ended_placement_is_excluded_from_frame_context',
  'future_text_mapping_does_not_leak_after_effective_end',
  'duration_does_not_add_start_timecode',
  'absolute_timecode_adds_start_timecode_once',
  'drop_frame_2997_skips_labels_at_minute',
  'drop_frame_2997_keeps_tenth_minute',
  'drop_frame_5994_skips_four_labels',
  'drop_frame_wraps_at_24_hours',
  'project_rail_uses_duration_formatter',
  'timeline_and_exports_use_absolute_formatter',
  'status_refreshes_stale_active_create',
  'status_refreshes_stale_active_update',
  'status_does_not_fail_for_unrelated_malformed_lock',
  'status_exposes_heartbeat_health',
  'status_snapshot_is_idempotent',
  'e2e_late_anchor_key_frame_is_visible',
  'e2e_project_recovery_disables_only_selected_project',
  'e2e_asset_integrity_notice_clears_after_reconcile',
  'e2e_24fps_and_duration_timecode_are_distinct',
  'e2e_audio_seek_and_end_cleanup',
  'e2e_409_and_503_do_not_create_persistent_project_block',
  'e2e_black_and_hold_previous_visual_modes',
];

async function sourceFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested: string[][] = await Promise.all(entries.map(async (entry): Promise<string[]> => {
    const path: string = join(directory, entry.name);
    if (entry.isDirectory()) return sourceFiles(path);
    return extname(entry.name) === '.ts' ? [path] : [];
  }));
  return nested.flat();
}

function declaredTestNames(source: string): string[] {
  return [...source.matchAll(/\b(?:it|test)\s*\(\s*(['"`])([^'"`]+)\1/gu)].map((match: RegExpMatchArray): string => match[2] as string);
}

const files: string[] = await sourceFiles('tests');
const sources: string[] = await Promise.all(files.map((file: string): Promise<string> => readFile(file, 'utf8')));
const names: string[] = sources.flatMap(declaredTestNames);
const counts: Map<string, number> = new Map<string, number>();
for (const name of names) counts.set(name, (counts.get(name) ?? 0) + 1);
const missing: string[] = REQUIRED_TEST_NAMES.filter((name: string): boolean => !counts.has(name));
const duplicates: string[] = REQUIRED_TEST_NAMES.filter((name: string): boolean => (counts.get(name) ?? 0) > 1);
const skipCount: number = sources.reduce((total: number, source: string): number => total + [...source.matchAll(/\b(?:describe|it|test)\.skip\s*\(/gu)].length, 0);
const onlyCount: number = sources.reduce((total: number, source: string): number => total + [...source.matchAll(/\b(?:describe|it|test)\.only\s*\(/gu)].length, 0);
const result = { required: REQUIRED_TEST_NAMES.length, missing: missing.length, duplicates: duplicates.length, skip: skipCount, only: onlyCount };
process.stdout.write(`${JSON.stringify(result)}\n`);
if (missing.length > 0 || duplicates.length > 0 || skipCount > 0 || onlyCount > 0) {
  throw contractError('REQUIRED_TEST_CONTRACT_FAILED', `필수 테스트 계약이 맞지 않습니다. missing=${missing.join(',') || '0'}, duplicates=${duplicates.join(',') || '0'}, skip=${skipCount}, only=${onlyCount}`, []);
}
